version: '2.2'

services:
  app_db:
    container_name: app_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=kr_db"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "SERVER_PORT=8080"
    expose:
      - "8081"
    restart: always
    networks:
      - app-network
  db2:
    container_name: db2
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kr_db
    ports:
      - "5433:5433"
    restart: always
    volumes:
      - ./db/shortcut/data3:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  web-root:

networks:
  app-network:
    driver: bridge