version: '2.2'

services:
  app_db:
    container_name: app_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=kr_db"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "SERVER_PORT=8080"
    expose:
      - "8081"
    depends_on:
      - nginx_db
    restart: always
    networks:
      - app-network

volumes:
  web-root:

networks:
  app-network:
    driver: bridge