version: '2.2'

services:
  nginx_db:
    container_name: nginx_db
    image: nginx:1.13
    restart: always
    ports:
      - 81:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
    networks:
      - app-network

  db_db:
    container_name: db_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data2
    networks:
      - app-network
  app_db:
    container_name: app_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=kr_db"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "SERVER_PORT=8080"
    expose:
      - "8080"
    depends_on:
      - nginx_db
    restart: no
    networks:
      - app-network

volumes:
  web-root:

networks:
  app-network:
    driver: bridge